/* eslint-disable no-shadow */

export enum TracksActionType {
  TRACKS_LOADING = 'TRACKS_LOADING',
  TRACKS_SUCCESS = 'TRACKS_SUCCESS',
  TRACKS_FAIL = 'TRACKS_FAIL',
}

export enum TestimonialsActionType {
  TESTIMONIALS_LOADING = 'TESTIMONIALS_LOADING',
  TESTIMONIALS_SUCCESS = 'TESTIMONIALS_SUCCESS',
  TESTIMONIALS_FAIL = 'TESTIMONIALS_FAIL',
}

export enum ActiveActionType {
  SET_ACTIVE_TRACK = 'SET_ACTIVE_TRACK',
  SET_ACTIVE_ORDER = 'SET_ACTIVE_ORDER',
  SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE',
  SET_ACTIVE_INPUT_VALUE = 'SET_ACTIVE_INPUT_VALUE',
}
